#!/bin/bash

WORKSPACE=/Users/tA88//Documents/workspace_muvibee/MuViBee.Backend/resources
JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Home

cd $WORKSPACE
rm MuViBee.properties
rm ./MuViBee_de.properties
rm ./MuViBee_ru.properties
rm ./MuViBee_tr.properties

$JAVA_HOME/bin/native2ascii -encoding UTF8 ./init_language/MuViBee_init.properties ./MuViBee.properties
$JAVA_HOME/bin/native2ascii -encoding UTF8 ./init_language/MuViBee_de_init.properties ./MuViBee_de.properties
$JAVA_HOME/bin/native2ascii -encoding UTF8 ./init_language/MuViBee_ru_init.properties ./MuViBee_ru.properties
$JAVA_HOME/bin/native2ascii -encoding UTF8 ./init_language/MuViBee_tr_init.properties ./MuViBee_tr.properties
